//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciID { get; set; }
        public Nullable<int> KullanciRolId { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public bool Aktif { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
