//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SutUretim
    {
        public int SutUretimID { get; set; }
        public int HayvanId { get; set; }
        public System.DateTime Tarih { get; set; }
        public int ZamanId { get; set; }
        public decimal Miktar { get; set; }
    
        public virtual Hayvan Hayvan { get; set; }
        public virtual Zaman Zaman { get; set; }
    }
}
